/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated.settings.account'
import { Route as AuthenticatedHomeEventsRouteImport } from './routes/_authenticated.home.events'
import { Route as AuthenticatedHomeCalendarsIndexRouteImport } from './routes/_authenticated.home.calendars.index'
import { Route as AuthenticatedAdminUsersIndexRouteImport } from './routes/_authenticated.admin.users.index'
import { Route as AuthenticatedHomeCalendarsCreateRouteImport } from './routes/_authenticated.home.calendars.create'
import { Route as AuthenticatedAdminUsersCreateRouteImport } from './routes/_authenticated.admin.users.create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeEventsRoute = AuthenticatedHomeEventsRouteImport.update({
  id: '/home/events',
  path: '/home/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeCalendarsIndexRoute =
  AuthenticatedHomeCalendarsIndexRouteImport.update({
    id: '/home/calendars/',
    path: '/home/calendars/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersIndexRoute =
  AuthenticatedAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeCalendarsCreateRoute =
  AuthenticatedHomeCalendarsCreateRouteImport.update({
    id: '/home/calendars/create',
    path: '/home/calendars/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersCreateRoute =
  AuthenticatedAdminUsersCreateRouteImport.update({
    id: '/admin/users/create',
    path: '/admin/users/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home/events': typeof AuthenticatedHomeEventsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/admin/users/create': typeof AuthenticatedAdminUsersCreateRoute
  '/home/calendars/create': typeof AuthenticatedHomeCalendarsCreateRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/home/calendars': typeof AuthenticatedHomeCalendarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home/events': typeof AuthenticatedHomeEventsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/admin/users/create': typeof AuthenticatedAdminUsersCreateRoute
  '/home/calendars/create': typeof AuthenticatedHomeCalendarsCreateRoute
  '/admin/users': typeof AuthenticatedAdminUsersIndexRoute
  '/home/calendars': typeof AuthenticatedHomeCalendarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/home/events': typeof AuthenticatedHomeEventsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/admin/users/create': typeof AuthenticatedAdminUsersCreateRoute
  '/_authenticated/home/calendars/create': typeof AuthenticatedHomeCalendarsCreateRoute
  '/_authenticated/admin/users/': typeof AuthenticatedAdminUsersIndexRoute
  '/_authenticated/home/calendars/': typeof AuthenticatedHomeCalendarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home/events'
    | '/settings/account'
    | '/admin/users/create'
    | '/home/calendars/create'
    | '/admin/users'
    | '/home/calendars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home/events'
    | '/settings/account'
    | '/admin/users/create'
    | '/home/calendars/create'
    | '/admin/users'
    | '/home/calendars'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/home/events'
    | '/_authenticated/settings/account'
    | '/_authenticated/admin/users/create'
    | '/_authenticated/home/calendars/create'
    | '/_authenticated/admin/users/'
    | '/_authenticated/home/calendars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/events': {
      id: '/_authenticated/home/events'
      path: '/home/events'
      fullPath: '/home/events'
      preLoaderRoute: typeof AuthenticatedHomeEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/calendars/': {
      id: '/_authenticated/home/calendars/'
      path: '/home/calendars'
      fullPath: '/home/calendars'
      preLoaderRoute: typeof AuthenticatedHomeCalendarsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/': {
      id: '/_authenticated/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home/calendars/create': {
      id: '/_authenticated/home/calendars/create'
      path: '/home/calendars/create'
      fullPath: '/home/calendars/create'
      preLoaderRoute: typeof AuthenticatedHomeCalendarsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/create': {
      id: '/_authenticated/admin/users/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AuthenticatedAdminUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHomeEventsRoute: typeof AuthenticatedHomeEventsRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedAdminUsersCreateRoute: typeof AuthenticatedAdminUsersCreateRoute
  AuthenticatedHomeCalendarsCreateRoute: typeof AuthenticatedHomeCalendarsCreateRoute
  AuthenticatedAdminUsersIndexRoute: typeof AuthenticatedAdminUsersIndexRoute
  AuthenticatedHomeCalendarsIndexRoute: typeof AuthenticatedHomeCalendarsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHomeEventsRoute: AuthenticatedHomeEventsRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedAdminUsersCreateRoute: AuthenticatedAdminUsersCreateRoute,
  AuthenticatedHomeCalendarsCreateRoute: AuthenticatedHomeCalendarsCreateRoute,
  AuthenticatedAdminUsersIndexRoute: AuthenticatedAdminUsersIndexRoute,
  AuthenticatedHomeCalendarsIndexRoute: AuthenticatedHomeCalendarsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
